name: Create Archive
on: [push]
# This is a comment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig .github'
    - name: Upload Release
      uses: ncipollo/release-action@main
      with:
        commit: main
        tag: ${{ steps.date.outputs.date }}
        artifacts: "release.zip"
        token: ${{ secrets.GH_TOKEN }}