name: Create Archive
on:  
  push:
    inputs:
      tags:
        - '*'
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig .github'
    - name: Upload Release
      uses: ncipollo/release-action@main
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GH_TOKEN }}